local util = require('core.util')

util.prequire('plugins.config.colorscheme')
util.prequire('plugins.config.common')
util.prequire('plugins.config.feline')
util.prequire('plugins.config.gitsigns')
util.prequire('plugins.config.indent_blankline')
util.prequire('plugins.config.lsp')
util.prequire('plugins.config.navic')
util.prequire('plugins.config.nvim_autopairs')
util.prequire('plugins.config.nvim_cmp')
util.prequire('plugins.config.nvim_tree')
util.prequire('plugins.config.telescope')
util.prequire('plugins.config.treesitter')
